// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Correlationc
arma::mat Correlationc(const arma::mat& coordsx, const arma::mat& coordsy, const arma::vec& theta, int covar, bool same);
RcppExport SEXP _radgp_Correlationc(SEXP coordsxSEXP, SEXP coordsySEXP, SEXP thetaSEXP, SEXP covarSEXP, SEXP sameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coordsx(coordsxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coordsy(coordsySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< bool >::type same(sameSEXP);
    rcpp_result_gen = Rcpp::wrap(Correlationc(coordsx, coordsy, theta, covar, same));
    return rcpp_result_gen;
END_RCPP
}
// gpkernel
arma::mat gpkernel(const arma::mat& coordsx, const arma::vec& theta, int covar);
RcppExport SEXP _radgp_gpkernel(SEXP coordsxSEXP, SEXP thetaSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coordsx(coordsxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(gpkernel(coordsx, theta, covar));
    return rcpp_result_gen;
END_RCPP
}
// make_candidates
arma::umat make_candidates(const arma::mat& w, const arma::uvec& indsort, unsigned int col, double rho);
RcppExport SEXP _radgp_make_candidates(SEXP wSEXP, SEXP indsortSEXP, SEXP colSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indsort(indsortSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type col(colSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(make_candidates(w, indsort, col, rho));
    return rcpp_result_gen;
END_RCPP
}
// neighbor_search
arma::field<arma::uvec> neighbor_search(const arma::mat& w, double rho);
RcppExport SEXP _radgp_neighbor_search(SEXP wSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbor_search(w, rho));
    return rcpp_result_gen;
END_RCPP
}
// dagbuild_from_nn
arma::field<arma::uvec> dagbuild_from_nn(const arma::field<arma::uvec>& Rset, const arma::mat& w);
RcppExport SEXP _radgp_dagbuild_from_nn(SEXP RsetSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type Rset(RsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(dagbuild_from_nn(Rset, w));
    return rcpp_result_gen;
END_RCPP
}
// radialndag
arma::field<arma::uvec> radialndag(const arma::mat& w, double rho);
RcppExport SEXP _radgp_radialndag(SEXP wSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(radialndag(w, rho));
    return rcpp_result_gen;
END_RCPP
}
// radial_neighbors_dag
Rcpp::List radial_neighbors_dag(const arma::mat& w, double rho);
RcppExport SEXP _radgp_radial_neighbors_dag(SEXP wSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(radial_neighbors_dag(w, rho));
    return rcpp_result_gen;
END_RCPP
}
// sparse_struct
arma::umat sparse_struct(const arma::field<arma::uvec>& dag, int nr);
RcppExport SEXP _radgp_sparse_struct(SEXP dagSEXP, SEXP nrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_struct(dag, nr));
    return rcpp_result_gen;
END_RCPP
}
// neighbor_search_testset
arma::field<arma::uvec> neighbor_search_testset(const arma::mat& wtrain, const arma::mat& wtest, double rho);
RcppExport SEXP _radgp_neighbor_search_testset(SEXP wtrainSEXP, SEXP wtestSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type wtrain(wtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wtest(wtestSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbor_search_testset(wtrain, wtest, rho));
    return rcpp_result_gen;
END_RCPP
}
// radgpbuild_testset
arma::field<arma::uvec> radgpbuild_testset(const arma::mat& wtrain, const arma::mat& wtest, double rho);
RcppExport SEXP _radgp_radgpbuild_testset(SEXP wtrainSEXP, SEXP wtestSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type wtrain(wtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wtest(wtestSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(radgpbuild_testset(wtrain, wtest, rho));
    return rcpp_result_gen;
END_RCPP
}
// radial_neighbors_dag_testset
Rcpp::List radial_neighbors_dag_testset(const arma::mat& wtrain, const arma::mat& wtest, double rho);
RcppExport SEXP _radgp_radial_neighbors_dag_testset(SEXP wtrainSEXP, SEXP wtestSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type wtrain(wtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wtest(wtestSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(radial_neighbors_dag_testset(wtrain, wtest, rho));
    return rcpp_result_gen;
END_RCPP
}
// radgp_response_predict
Rcpp::List radgp_response_predict(const arma::mat& cout, const arma::vec& y, const arma::mat& coords, double rho, const arma::mat& theta_mcmc, int covar, int num_threads);
RcppExport SEXP _radgp_radgp_response_predict(SEXP coutSEXP, SEXP ySEXP, SEXP coordsSEXP, SEXP rhoSEXP, SEXP theta_mcmcSEXP, SEXP covarSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cout(coutSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_mcmc(theta_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(radgp_response_predict(cout, y, coords, rho, theta_mcmc, covar, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// vecchiagp_response_predict
arma::mat vecchiagp_response_predict(const arma::mat& cout, const arma::vec& y, const arma::mat& coords, const arma::field<arma::uvec>& dag, const arma::mat& theta_mcmc, int covar, int num_threads);
RcppExport SEXP _radgp_vecchiagp_response_predict(SEXP coutSEXP, SEXP ySEXP, SEXP coordsSEXP, SEXP dagSEXP, SEXP theta_mcmcSEXP, SEXP covarSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cout(coutSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_mcmc(theta_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(vecchiagp_response_predict(cout, y, coords, dag, theta_mcmc, covar, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// radgp_latent_predict
Rcpp::List radgp_latent_predict(const arma::mat& cout, const arma::mat& w, const arma::mat& coords, double rho, const arma::mat& theta_mcmc, int covar, int num_threads);
RcppExport SEXP _radgp_radgp_latent_predict(SEXP coutSEXP, SEXP wSEXP, SEXP coordsSEXP, SEXP rhoSEXP, SEXP theta_mcmcSEXP, SEXP covarSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cout(coutSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_mcmc(theta_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(radgp_latent_predict(cout, w, coords, rho, theta_mcmc, covar, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// vecchiagp_latent_predict
arma::mat vecchiagp_latent_predict(const arma::mat& cout, const arma::mat& w, const arma::mat& coords, const arma::field<arma::uvec>& dag, const arma::mat& theta_mcmc, int covar, int num_threads);
RcppExport SEXP _radgp_vecchiagp_latent_predict(SEXP coutSEXP, SEXP wSEXP, SEXP coordsSEXP, SEXP dagSEXP, SEXP theta_mcmcSEXP, SEXP covarSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cout(coutSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_mcmc(theta_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(vecchiagp_latent_predict(cout, w, coords, dag, theta_mcmc, covar, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// hmat_from_dag
Eigen::SparseMatrix<double> hmat_from_dag(const arma::mat& coords, const arma::field<arma::uvec>& dag, const arma::vec& theta, int covar);
RcppExport SEXP _radgp_hmat_from_dag(SEXP coordsSEXP, SEXP dagSEXP, SEXP thetaSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(hmat_from_dag(coords, dag, theta, covar));
    return rcpp_result_gen;
END_RCPP
}
// pred_from_dag
arma::vec pred_from_dag(const arma::mat& coords, const arma::field<arma::uvec>& dag, const arma::vec& theta, const arma::vec& urng, int covar);
RcppExport SEXP _radgp_pred_from_dag(SEXP coordsSEXP, SEXP dagSEXP, SEXP thetaSEXP, SEXP urngSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type urng(urngSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_from_dag(coords, dag, theta, urng, covar));
    return rcpp_result_gen;
END_RCPP
}
// radgp_latent
Rcpp::List radgp_latent(const arma::vec& y, const arma::mat& coords, double rho, int mcmc, int num_threads, const arma::vec& theta_init, double tausq_init, double metrop_sd, const arma::mat& theta_unif_bounds, const arma::vec& tausq_prior, int covar, int num_prints);
RcppExport SEXP _radgp_radgp_latent(SEXP ySEXP, SEXP coordsSEXP, SEXP rhoSEXP, SEXP mcmcSEXP, SEXP num_threadsSEXP, SEXP theta_initSEXP, SEXP tausq_initSEXP, SEXP metrop_sdSEXP, SEXP theta_unif_boundsSEXP, SEXP tausq_priorSEXP, SEXP covarSEXP, SEXP num_printsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type tausq_init(tausq_initSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd(metrop_sdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_unif_bounds(theta_unif_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tausq_prior(tausq_priorSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_prints(num_printsSEXP);
    rcpp_result_gen = Rcpp::wrap(radgp_latent(y, coords, rho, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints));
    return rcpp_result_gen;
END_RCPP
}
// daggp_custom_latent
Rcpp::List daggp_custom_latent(const arma::vec& y, const arma::mat& coords, const arma::field<arma::uvec>& dag, int mcmc, int num_threads, const arma::vec& theta_init, double tausq_init, double metrop_sd, const arma::mat& theta_unif_bounds, const arma::vec& tausq_prior, int covar, int num_prints);
RcppExport SEXP _radgp_daggp_custom_latent(SEXP ySEXP, SEXP coordsSEXP, SEXP dagSEXP, SEXP mcmcSEXP, SEXP num_threadsSEXP, SEXP theta_initSEXP, SEXP tausq_initSEXP, SEXP metrop_sdSEXP, SEXP theta_unif_boundsSEXP, SEXP tausq_priorSEXP, SEXP covarSEXP, SEXP num_printsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type tausq_init(tausq_initSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd(metrop_sdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_unif_bounds(theta_unif_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tausq_prior(tausq_priorSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_prints(num_printsSEXP);
    rcpp_result_gen = Rcpp::wrap(daggp_custom_latent(y, coords, dag, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints));
    return rcpp_result_gen;
END_RCPP
}
// radgp_response
Rcpp::List radgp_response(const arma::vec& y, const arma::mat& coords, double rho, int mcmc, int num_threads, const arma::vec& theta_init, double metrop_sd, const arma::mat& theta_unif_bounds, const arma::vec& tausq_prior, int covar, int num_prints);
RcppExport SEXP _radgp_radgp_response(SEXP ySEXP, SEXP coordsSEXP, SEXP rhoSEXP, SEXP mcmcSEXP, SEXP num_threadsSEXP, SEXP theta_initSEXP, SEXP metrop_sdSEXP, SEXP theta_unif_boundsSEXP, SEXP tausq_priorSEXP, SEXP covarSEXP, SEXP num_printsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd(metrop_sdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_unif_bounds(theta_unif_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tausq_prior(tausq_priorSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_prints(num_printsSEXP);
    rcpp_result_gen = Rcpp::wrap(radgp_response(y, coords, rho, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints));
    return rcpp_result_gen;
END_RCPP
}
// daggp_custom
Rcpp::List daggp_custom(const arma::vec& y, const arma::mat& coords, const arma::field<arma::uvec>& dag, int mcmc, int num_threads, const arma::vec& theta_init, double metrop_sd, const arma::mat& theta_unif_bounds, const arma::vec& tausq_prior, int covar, int num_prints);
RcppExport SEXP _radgp_daggp_custom(SEXP ySEXP, SEXP coordsSEXP, SEXP dagSEXP, SEXP mcmcSEXP, SEXP num_threadsSEXP, SEXP theta_initSEXP, SEXP metrop_sdSEXP, SEXP theta_unif_boundsSEXP, SEXP tausq_priorSEXP, SEXP covarSEXP, SEXP num_printsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd(metrop_sdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type theta_unif_bounds(theta_unif_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tausq_prior(tausq_priorSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_prints(num_printsSEXP);
    rcpp_result_gen = Rcpp::wrap(daggp_custom(y, coords, dag, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints));
    return rcpp_result_gen;
END_RCPP
}
// radgp_build
Rcpp::List radgp_build(const arma::mat& coords, const arma::vec& theta, double rho, int covar);
RcppExport SEXP _radgp_radgp_build(SEXP coordsSEXP, SEXP thetaSEXP, SEXP rhoSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(radgp_build(coords, theta, rho, covar));
    return rcpp_result_gen;
END_RCPP
}
// vecchiagp_build
Rcpp::List vecchiagp_build(const arma::mat& coords, const arma::vec& theta, const arma::field<arma::uvec>& dag, int covar);
RcppExport SEXP _radgp_vecchiagp_build(SEXP coordsSEXP, SEXP thetaSEXP, SEXP dagSEXP, SEXP covarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    rcpp_result_gen = Rcpp::wrap(vecchiagp_build(coords, theta, dag, covar));
    return rcpp_result_gen;
END_RCPP
}
// daggp_negdens
double daggp_negdens(const arma::vec& y, const arma::mat& coords, const arma::field<arma::uvec>& dag, const arma::vec& theta, int covar, int num_threads);
RcppExport SEXP _radgp_daggp_negdens(SEXP ySEXP, SEXP coordsSEXP, SEXP dagSEXP, SEXP thetaSEXP, SEXP covarSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type dag(dagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(daggp_negdens(y, coords, dag, theta, covar, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_radgp_Correlationc", (DL_FUNC) &_radgp_Correlationc, 5},
    {"_radgp_gpkernel", (DL_FUNC) &_radgp_gpkernel, 3},
    {"_radgp_make_candidates", (DL_FUNC) &_radgp_make_candidates, 4},
    {"_radgp_neighbor_search", (DL_FUNC) &_radgp_neighbor_search, 2},
    {"_radgp_dagbuild_from_nn", (DL_FUNC) &_radgp_dagbuild_from_nn, 2},
    {"_radgp_radialndag", (DL_FUNC) &_radgp_radialndag, 2},
    {"_radgp_radial_neighbors_dag", (DL_FUNC) &_radgp_radial_neighbors_dag, 2},
    {"_radgp_sparse_struct", (DL_FUNC) &_radgp_sparse_struct, 2},
    {"_radgp_neighbor_search_testset", (DL_FUNC) &_radgp_neighbor_search_testset, 3},
    {"_radgp_radgpbuild_testset", (DL_FUNC) &_radgp_radgpbuild_testset, 3},
    {"_radgp_radial_neighbors_dag_testset", (DL_FUNC) &_radgp_radial_neighbors_dag_testset, 3},
    {"_radgp_radgp_response_predict", (DL_FUNC) &_radgp_radgp_response_predict, 7},
    {"_radgp_vecchiagp_response_predict", (DL_FUNC) &_radgp_vecchiagp_response_predict, 7},
    {"_radgp_radgp_latent_predict", (DL_FUNC) &_radgp_radgp_latent_predict, 7},
    {"_radgp_vecchiagp_latent_predict", (DL_FUNC) &_radgp_vecchiagp_latent_predict, 7},
    {"_radgp_hmat_from_dag", (DL_FUNC) &_radgp_hmat_from_dag, 4},
    {"_radgp_pred_from_dag", (DL_FUNC) &_radgp_pred_from_dag, 5},
    {"_radgp_radgp_latent", (DL_FUNC) &_radgp_radgp_latent, 12},
    {"_radgp_daggp_custom_latent", (DL_FUNC) &_radgp_daggp_custom_latent, 12},
    {"_radgp_radgp_response", (DL_FUNC) &_radgp_radgp_response, 11},
    {"_radgp_daggp_custom", (DL_FUNC) &_radgp_daggp_custom, 11},
    {"_radgp_radgp_build", (DL_FUNC) &_radgp_radgp_build, 4},
    {"_radgp_vecchiagp_build", (DL_FUNC) &_radgp_vecchiagp_build, 4},
    {"_radgp_daggp_negdens", (DL_FUNC) &_radgp_daggp_negdens, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_radgp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
