# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Correlationc <- function(coordsx, coordsy, theta, same) {
    .Call(`_radgp_Correlationc`, coordsx, coordsy, theta, same)
}

gpkernel <- function(coordsx, theta) {
    .Call(`_radgp_gpkernel`, coordsx, theta)
}

make_candidates <- function(w, indsort, col, rho) {
    .Call(`_radgp_make_candidates`, w, indsort, col, rho)
}

neighbor_search <- function(w, rho) {
    .Call(`_radgp_neighbor_search`, w, rho)
}

dagbuild_from_nn <- function(Rset, layers, M, w, rho) {
    .Call(`_radgp_dagbuild_from_nn`, Rset, layers, M, w, rho)
}

Raptdagbuild <- function(w, rho) {
    .Call(`_radgp_Raptdagbuild`, w, rho)
}

sparse_struct <- function(dag, nr) {
    .Call(`_radgp_sparse_struct`, dag, nr)
}

neighbor_search_testset <- function(wtrain, wtest, rho) {
    .Call(`_radgp_neighbor_search_testset`, wtrain, wtest, rho)
}

dagbuild_from_nn_testset <- function(Rset, ntrain, layers, Mmin, wtrain, wtest) {
    .Call(`_radgp_dagbuild_from_nn_testset`, Rset, ntrain, layers, Mmin, wtrain, wtest)
}

Raptdagbuild_testset <- function(wtrain, wtest, rho, M) {
    .Call(`_radgp_Raptdagbuild_testset`, wtrain, wtest, rho, M)
}

aptdaggp_response_predict <- function(cout, y, coords, rho, theta_mcmc, M, num_threads) {
    .Call(`_radgp_aptdaggp_response_predict`, cout, y, coords, rho, theta_mcmc, M, num_threads)
}

vecchiagp_response_predict <- function(cout, y, coords, dag, theta_mcmc, num_threads) {
    .Call(`_radgp_vecchiagp_response_predict`, cout, y, coords, dag, theta_mcmc, num_threads)
}

aptdaggp_latent_predict <- function(cout, w, coords, rho, theta_mcmc, M, num_threads) {
    .Call(`_radgp_aptdaggp_latent_predict`, cout, w, coords, rho, theta_mcmc, M, num_threads)
}

vecchiagp_latent_predict <- function(cout, w, coords, dag, theta_mcmc, num_threads) {
    .Call(`_radgp_vecchiagp_latent_predict`, cout, w, coords, dag, theta_mcmc, num_threads)
}

hmat_from_dag <- function(coords, dag, theta) {
    .Call(`_radgp_hmat_from_dag`, coords, dag, theta)
}

pred_from_dag <- function(coords, dag, theta, urng) {
    .Call(`_radgp_pred_from_dag`, coords, dag, theta, urng)
}

aptdaggp_latent <- function(y, coords, rho, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints = 10L) {
    .Call(`_radgp_aptdaggp_latent`, y, coords, rho, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints)
}

aptdaggp_custom_latent <- function(y, coords, dag, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints = 10L) {
    .Call(`_radgp_aptdaggp_custom_latent`, y, coords, dag, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints)
}

aptdaggp_response <- function(y, coords, rho, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints = 10L) {
    .Call(`_radgp_aptdaggp_response`, y, coords, rho, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints)
}

aptdaggp_custom <- function(y, coords, dag, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints = 10L) {
    .Call(`_radgp_aptdaggp_custom`, y, coords, dag, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, num_prints)
}

aptdaggp <- function(coords, theta, rho) {
    .Call(`_radgp_aptdaggp`, coords, theta, rho)
}

vecchiagp <- function(coords, theta, dag) {
    .Call(`_radgp_vecchiagp`, coords, theta, dag)
}

daggp_negdens <- function(y, coords, dag, theta, num_threads) {
    .Call(`_radgp_daggp_negdens`, y, coords, dag, theta, num_threads)
}

