# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Correlationc <- function(coordsx, coordsy, theta, covar, same) {
    .Call(`_radgp_Correlationc`, coordsx, coordsy, theta, covar, same)
}

gpkernel <- function(coordsx, theta, covar) {
    .Call(`_radgp_gpkernel`, coordsx, theta, covar)
}

make_candidates <- function(w, indsort, col, rho) {
    .Call(`_radgp_make_candidates`, w, indsort, col, rho)
}

neighbor_search <- function(w, rho) {
    .Call(`_radgp_neighbor_search`, w, rho)
}

dagbuild_from_nn <- function(Rset, w) {
    .Call(`_radgp_dagbuild_from_nn`, Rset, w)
}

radialndag <- function(w, rho) {
    .Call(`_radgp_radialndag`, w, rho)
}

radial_neighbors_dag <- function(w, rho) {
    .Call(`_radgp_radial_neighbors_dag`, w, rho)
}

sparse_struct <- function(dag, nr) {
    .Call(`_radgp_sparse_struct`, dag, nr)
}

neighbor_search_testset <- function(wtrain, wtest, rho) {
    .Call(`_radgp_neighbor_search_testset`, wtrain, wtest, rho)
}

radgpbuild_testset <- function(wtrain, wtest, rho) {
    .Call(`_radgp_radgpbuild_testset`, wtrain, wtest, rho)
}

radial_neighbors_dag_testset <- function(wtrain, wtest, rho) {
    .Call(`_radgp_radial_neighbors_dag_testset`, wtrain, wtest, rho)
}

radgp_response_predict <- function(cout, y, coords, rho, theta_mcmc, covar, num_threads) {
    .Call(`_radgp_radgp_response_predict`, cout, y, coords, rho, theta_mcmc, covar, num_threads)
}

vecchiagp_response_predict <- function(cout, y, coords, dag, theta_mcmc, covar, num_threads) {
    .Call(`_radgp_vecchiagp_response_predict`, cout, y, coords, dag, theta_mcmc, covar, num_threads)
}

radgp_latent_predict <- function(cout, w, coords, rho, theta_mcmc, covar, num_threads) {
    .Call(`_radgp_radgp_latent_predict`, cout, w, coords, rho, theta_mcmc, covar, num_threads)
}

vecchiagp_latent_predict <- function(cout, w, coords, dag, theta_mcmc, covar, num_threads) {
    .Call(`_radgp_vecchiagp_latent_predict`, cout, w, coords, dag, theta_mcmc, covar, num_threads)
}

hmat_from_dag <- function(coords, dag, theta, covar) {
    .Call(`_radgp_hmat_from_dag`, coords, dag, theta, covar)
}

pred_from_dag <- function(coords, dag, theta, urng, covar) {
    .Call(`_radgp_pred_from_dag`, coords, dag, theta, urng, covar)
}

radgp_latent <- function(y, coords, rho, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints = 10L) {
    .Call(`_radgp_radgp_latent`, y, coords, rho, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints)
}

daggp_custom_latent <- function(y, coords, dag, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints = 10L) {
    .Call(`_radgp_daggp_custom_latent`, y, coords, dag, mcmc, num_threads, theta_init, tausq_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints)
}

radgp_response <- function(y, coords, rho, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints = 10L) {
    .Call(`_radgp_radgp_response`, y, coords, rho, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints)
}

daggp_custom <- function(y, coords, dag, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints = 10L) {
    .Call(`_radgp_daggp_custom`, y, coords, dag, mcmc, num_threads, theta_init, metrop_sd, theta_unif_bounds, tausq_prior, covar, num_prints)
}

radgp_build <- function(coords, theta, rho, covar) {
    .Call(`_radgp_radgp_build`, coords, theta, rho, covar)
}

vecchiagp_build <- function(coords, theta, dag, covar) {
    .Call(`_radgp_vecchiagp_build`, coords, theta, dag, covar)
}

daggp_negdens <- function(y, coords, dag, theta, covar, num_threads) {
    .Call(`_radgp_daggp_negdens`, y, coords, dag, theta, covar, num_threads)
}

